"""Add role to users and rename customer to user

Revision ID: ff88359529c3
Revises: f9f493249029
Create Date: 2025-11-05 11:10:35.978586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff88359529c3'
down_revision: Union[str, Sequence[str], None] = 'f9f493249029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    
    op.drop_constraint('bookings_customer_id_fkey', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'customer_id')
    op.drop_table('customers')
    op.create_table(
        'users',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Enum('admin', 'customer', name='user_roles'), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('user_id')
    )

  
    op.add_column('bookings', sa.Column('user_id', sa.UUID(), nullable=False))


    op.create_unique_constraint(None, 'bookings', ['booking_id'])

 
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['user_id'])


    op.create_unique_constraint(None, 'rooms', ['room_id'])



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.add_column('bookings', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_customer_id_fkey'), 'bookings', 'customers', ['customer_id'], ['customer_id'])
    op.drop_constraint(None, 'bookings', type_='unique')
    op.drop_column('bookings', 'user_id')
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('customers_pkey')),
    sa.UniqueConstraint('email', name=op.f('customers_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('users')
    # ### end Alembic commands ###
